# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

baseURL = "https://jairam.dev/"
theme = "blowfish"
languageCode = "en"

enableRobotsTXT = true
pagination.pagerSize = 10
summaryLength = 0

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
