# -- Theme Options --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/

colorScheme = "slate"
defaultAppearance = "dark"
autoSwitchAppearance = true
defaultBackgroundImage = "img/hero.svg"

enableSearch = true
enableCodeCopy = true
enableImageLazyLoading = true

fingerprintAlgorithm = "sha256"

[header]
  layout = "fixed"

[footer]
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "background"
  homepageImage = "img/hero.svg"
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "/posts/"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true

[article]
  showHero = true
  heroStyle = "background"
  layoutBackgroundHeaderSpace = false
  showDate = true
  showDateUpdated = true
  showAuthor = false
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = false
  showComments = true
  showSummary = true
  showRelatedContent = true
  relatedContentLimit = 3
  sharingLinks = ["linkedin", "twitter", "reddit", "email"]

[list]
  showBreadcrumbs = false
  showSummary = true
  showTableOfContents = false
  showTaxonomies = true
  groupByYear = true
  showCards = true
  cardView = true
  paginationWidth = 1

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
