# Site settings
title: Jairam Chandar
author: Jairam Chandar
email: contact@jairam.me
description: Musings of a Software Engineer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jairamc.github.io" # the base hostname & protocol for your site
twitter_username: jairamc
github_username:  jairamc

# Build settings
# markdown: redcarpet

plugins:
  - jemoji
  - jekyll-redirect-from
