# Site settings
title: Jairam Chandar
author: Jairam Chandar
email: contact@jairam.dev
description: Musings of a Software Engineer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jairam.dev" # the base hostname & protocol for your site
twitter_username: jairamc
github_username:  jairamc

# Set this to a github repository to be used to host comments.
github_comments_repository: jairamc/blog-comments

# Build settings
# markdown: redcarpet

plugins:
  - jemoji
  - jekyll-redirect-from
